### ISSUE TITLE
Is it postgres_set works?

### ISSUE THREAD

**Issue by xronos** [FRiCKLE/ngx_postgres#2]
I had tried this configuratio for my project:

postgres_pass database;
postgres_query "SELECT id FROM articles WHERE slug='$slug' LIMIT 1";
postgres_set $id 0 0;
postgres_output none;

When i try to use $id for rewrite operator it returns nothing:
rewrite  ^/(.*)$  /$id  permanent; => redirects to "/" but not /$id

When i try echo it, it returns nothing:
echo "id = '$id'"; => id=''

But when i try example from your tests with header, it works:
add_header "X-ID" $id; 

Why it is? Why i can`t get variable value?

**Comment by ghost** [comment]
I was able to get this working with the following stack:

```         
nginx-eval-module-2016.06.10  
openssl-1.0.2l
echo-nginx-module-0.61  
ngx_devel_kit-0.3.0           
pcre-8.41                   
zlib-1.2.11
nginx-1.13.6            
ngx_postgres-1.0rc7           
set-misc-nginx-module-0.31
```

Url trigger `somehost.com?subentity_slug=foo&entity_id=bar`

```
  location /subentity {
    eval_subrequest_in_memory off;

    eval $subentity_id {
      postgres_pass pg_backend;
      postgres_query  "SELECT subentity_id from entity_routing where 
          slug = '$arg_subentity_slug' and entity_id = '$arg_entity_id'";
      postgres_output value;
    }

    if ($subentity_id = "") {
      return 404;
    }

    if ($subentity_id != "") {
      return 301 http://someotherbiz.com/?entity_id=$arg_entity_id&subentity_id=$subentity_id;
    }
  }
```
