### ISSUE TITLE
Serializing Postgres array into JSON array

### ISSUE THREAD

**Issue by nepsilon** [FRiCKLE/ngx_postgres#43]
Any plan to have Postgres' array column type serialized into a JSON array instead of a string?

**Comment by agentzh** [comment]
@nepsilon I think it's better to be a feature in one of those `lua-resty-*` libraries for PostgreSQL based on ngx_lua's cosockets, which can be much more flexible. Like this:

https://github.com/leafo/pgmoon

(though I have my own plans on a lua-resty-postgresql library).

**Comment by buddy-ekb** [comment]
There is another approach with fresh postgres servers (9.2+): query returns a JSON-value while a client does something like JSON.parse() on the result. Though this somehow tangles the query text it indeed simplifies further data processing.

**Comment by nepsilon** [comment]
@buddy-ekb Thanks for the tip. I'll look into it :+1:

**Comment by nepsilon** [comment]
That fixed it. Thanks. I'm closing the issue.
